from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import include, url
from django.contrib import admin

from app.views import *
from users.views import *

from project.routers import HybridRouter
from django_mongoengine import mongo_admin


# We use a single global DRF Router that routes views from all apps in project
router = HybridRouter()

# app views and viewsets
router.register(r'tool', ToolViewSet, r"tool")
router.register(r'author', AuthorViewSet, r"author")
router.register(r'book', BookViewSet, r"book")
#router.register(r'user', UserViewSet, r"user")
#router.add_api_view(r'user', url(r'^user/$', UserViewSet.as_view(), name=r"user"))
#router.add_api_view(r'updateuser', url(r'^updateuser/$', UserUpdateView.as_view(), name=r"updateuser"))
#router.register(r'updateuser', UserUpdateView, r"updateuser")
#router.add_api_view(r'auth', url(r'^auth/$', ObtainAuthToken.as_view(), name=r"auth"))
#router.add_api_view(r'updateuser/', url(r'^updateuser/$', UserUpdateView.as_view(), name=r"updateuser"))
#router.add_api_view(r'signup/', url(r'^signup/$', SignUpView.as_view(), name=r"signup"))
#router.add_api_view(r'validateemail/', url(r'^validateemail/$', ValidateEmailView.as_view(), name=r"validateemail"))

router.add_api_view(r'rest-auth/logout/', url(r'^rest-auth/logout/$', LogoutView.as_view(), name=r"logout"))
router.add_api_view(r'rest-auth/login/', url(r'^rest-auth/login/$', LoginView.as_view(), name=r"login"))
router.add_api_view(r'rest-auth/registration/', url(r'^rest-auth/registration/$', SignUpView.as_view(), name=r"signup"))
router.add_api_view(r'rest-auth/password/change/', url(r'^rest-auth/password/change/$', PasswordChangeView.as_view(), name=r"pwd_change"))
router.add_api_view(r'rest-auth/registration/verify-email/', url(r'^rest-auth/registration/verify-email/$', ValidateEmailView.as_view(), name=r"verify_email"))
router.add_api_view(r'rest-auth/user/', url(r'^rest-auth/user/$', UserView.as_view(), name=r"user_profile"))

router.add_api_view(r'rest-auth/password/reset/', url(r'^rest-auth/password/reset/$', ResetPasswordView.as_view(), name=r"pwd_reset"))
router.add_api_view(r'rest-auth/password/change/confirm/', url(r'^rest-auth/password/change/confirm/$', ConfirmPasswordView.as_view(), name=r"pwd_confirm"))

"""
LOGIN: `${ROOT_URL}rest-auth/login/`,
    SIGNUP: `${ROOT_URL}rest-auth/registration/`,
    CHANGE_PASSWORD: `${ROOT_URL}rest-auth/password/change/`,
    RESET_PASSWORD: `${ROOT_URL}rest-auth/password/reset/`,
    RESET_PASSWORD_CONFIRM: `${ROOT_URL}rest-auth/password/reset/confirm/`,
    USER_ACTIVATION: `${ROOT_URL}rest-auth/registration/verify-email/`,
    USER_PROFILE: `${ROOT_URL}rest-auth/user/`,
"""

urlpatterns = [
    # default django admin interface (currently unused)
    url(r'^admin/', include(mongo_admin.site.urls)),

    # root view of our REST api, generated by Django REST Framework's router
    url(r'^api/', include(router.urls, namespace='api')),

    # index page should be served by django to set cookies, headers etc.
    url(r'^$', index_view, {}, name='index'),
]

# let django built-in server serve static and media content
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
